parameters:
#    politikportal.example.class: Politix\PolitikportalBundle\Example

services:
#    politikportal.example:
#        class: %politikportal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
